### PR TITLE
Updated Forge Version

### PR DESCRIPTION
**Pull request by DinnerBeef**
Updated forge after breaking changes

ok I pulled before pushing this time

### CODE REVIEW

**Review by Gegy — APPROVED** [review]
Looks good, thank you!! Is it worth updating the minimum Forge dependency too?

**Comment by DinnerBeef** [comment]
O yea that would be a good idea

**Comment by DinnerBeef** [comment]
O wait though. This mod does not require a minimum forge version on any other version of it so I don't see point in adding it

**Comment by Cojomax99** [comment]
Thanks DB :)

**Pull request merged**
